<?php
$cfg = array(
	'apiKey'=>REQUIRED,
	'url'=>request::uri(array('absolute'=>true)),
	'userAgent'=>'nyroFwk/'.NYROVERSION.' akismet/1.1',
	'apiPort'=>80,
	'apiServer'=>'rest.akismet.com',
	'apiVersion'=>'1.1',
	'comment'=>array(
		'comment_type'=>'comment',
		'comment_author'=>'',
		'comment_author_email'=>'',
		'comment_author_url'=>'',
		'comment_content'=>'',
		'user_ip'=>request::getIp(),
		'referrer'=>isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : null,
	),
	'ignoreServerVars'=>array(
		'HTTP_COOKIE',
		'HTTP_USER_AGENT',
		'HTTP_X_FORWARDED_FOR',
		'HTTP_X_FORWARDED_HOST',
		'HTTP_MAX_FORWARDS',
		'HTTP_X_FORWARDED_SERVER',
		'REDIRECT_STATUS',
		'SERVER_PORT',
		'PATH',
		'DOCUMENT_ROOT',
		'SERVER_ADMIN',
		'QUERY_STRING',
		'PHP_SELF',
		'REMOTE_ADDR',
	),
);