<?php
$cfg = array(
	'file'=>null,
	'fileSave'=>null,
	'fileSaveAdd'=>null,
	'autoFileSave'=>true,
	'w'=>0,
	'h'=>0,
	'bgColor'=>'ffffff',
	'fit'=>false,
	'resizeSmaller'=>true,
	'mask'=>null,
	'rebuild'=>false,
	'grayFilter'=>false,
	'filters'=>array(),
	'html'=>false,
	'alt'=>'Image',
	'htmlDefOptions'=>array(),
	'autoExt'=>array('gif', 'jpg', 'png'),
	'mime'=>array(
		'image/jpeg',
        'image/png',
        'image/x-png',
        'image/pjpeg',
	),
);