<?php
$cfg = array(
	'required'=>true,
	'name'=>REQUIRED,
	'dir'=>FILESROOT,
	'subdir'=>'uploads',
	'autoSave'=>true,
	'current'=>'',
	'deleteCurrent'=>true,
	'helperPrm'=>array(
		'view'=>array(
			'w'=>300,
			'h'=>150,
			'useMaxResize'=>true,
			'resizeSmaller'=>false,
			'fileSaveAdd'=>'admin',
		),
	),
	'previewPrm'=>array(
		'target'=>'_blank'
	),
	'previewText'=>false
);