<?php
$cfg = array(
	'required'=>true,
	'name'=>REQUIRED,
	'dir'=>FILESROOT,
	'subdir'=>'uploads',
	'autoSave'=>true,
	'current'=>'',
	'deleteCurrent'=>true,
	'helperPrm'=>array(
		'view'=>array(
			'h'=>200,
			'w'=>0,
			'fileSaveAdd'=>'admin',
		),
	),
	'previewPrm'=>array(
		'target'=>'_blank'
	),
	'previewText'=>false
);